"use client";
/**
 * Big Cycle tab — composite heat vs what the market did next, plus the
 * click-to-drill episode replay (the backtest case study, generalized).
 *
 * Data = src/data/backtest-panel.json, the monthly point-in-time replay
 * of the production factor math (regenerated by `npm run backtest`).
 */
import { useEffect, useMemo, useState } from "react";
import panelJson from "@/data/backtest-panel.json";
import {
  PanelMonth, SC_STATUS_COLOR, SC_STATUS_NAME,
  useTooltip, recessionBands, useRightPinnedScroll,
} from "./common";

const PANEL = panelJson as PanelMonth[];

const WINDOWS = [
  { key: "5Y", months: 60, ppm: 14 },
  { key: "10Y", months: 120, ppm: 7 },
  { key: "20Y", months: 240, ppm: 3.5 },
  { key: "50Y", months: 600, ppm: 1.6 },
  { key: "MAX", months: Infinity, ppm: 0 }, // 0 → fit container
] as const;

const EPISODES = [
  { key: "1970s", title: "1973–75 oil shock", from: "1972-06", to: "1975-06" },
  { key: "volcker", title: "Volcker 1979–82", from: "1979-01", to: "1982-12" },
  { key: "2001", title: "Dot-com / 2001", from: "2000-01", to: "2002-06" },
  { key: "gfc", title: "GFC 2007–09", from: "2007-01", to: "2009-06" },
  { key: "covid", title: "COVID 2020", from: "2019-06", to: "2020-12" },
  { key: "2022", title: "2022 bear", from: "2021-06", to: "2023-03" },
  { key: "2024", title: "2024 Sahm alarm", from: "2024-01", to: "2025-01" },
  { key: "now", title: "Last 18 months", from: PANEL[Math.max(0, PANEL.length - 18)].t, to: PANEL[PANEL.length - 1].t },
];

export default function HeatTimeline() {
  const [win, setWin] = useState<(typeof WINDOWS)[number]["key"]>("20Y");
  const [episode, setEpisode] = useState<string | null>(null);
  const { show, hide, node } = useTooltip();
  const { ref, pin } = useRightPinnedScroll();

  const w = WINDOWS.find(x => x.key === win)!;
  const months = PANEL;
  const n = months.length;
  const ppm = w.ppm || 0;
  const fit = w.key === "MAX" || n * ppm < 940;
  const width = fit ? 940 : Math.round(n * ppm);
  const effPpm = width / n;
  const H1 = 170, H2 = 120, PT = 8, PB = 18, AX = 34;

  useEffect(() => { if (!fit) pin(); }, [win, fit, pin]);

  const xAt = (i: number) => i * effPpm + effPpm / 2;
  const yHeat = (v: number) => PT + (1 - v / 100) * (H1 - PT - PB);
  const yDD = (v: number) => PT + (v / -60) * (H2 - PT - PB);

  const cyclePts = useMemo(() => months.map((m, i) => `${xAt(i).toFixed(1)},${yHeat(m.hc ?? 0).toFixed(1)}`).join(" "), [effPpm]);
  const sovPts = useMemo(() => months.map((m, i) => `${xAt(i).toFixed(1)},${yHeat(m.hs ?? 0).toFixed(1)}`).join(" "), [effPpm]);
  const heatArea = useMemo(() => `M${xAt(0)},${yHeat(0)} L${cyclePts.replace(/ /g, " L")} L${xAt(n - 1)},${yHeat(0)} Z`, [cyclePts]);
  const ddPts = useMemo(() =>
    months.map((m, i) => (m.f == null ? null : `${xAt(i).toFixed(1)},${yDD(m.f).toFixed(1)}`)).filter(Boolean).join(" "), [effPpm]);

  const yearLabels = useMemo(() => {
    const step = effPpm >= 7 ? 1 : effPpm >= 3 ? 3 : effPpm >= 1.4 ? 5 : 10;
    return months.map((m, i) => {
      const [yy, mm] = m.t.split("-");
      return mm === "01" && Number(yy) % step === 0 ? { i, yy } : null;
    }).filter((x): x is { i: number; yy: string } => x != null);
  }, [effPpm]);

  const hover = (e: React.MouseEvent<SVGSVGElement>) => {
    const svg = e.currentTarget;
    const r = svg.getBoundingClientRect();
    const i = Math.max(0, Math.min(n - 1, Math.floor(((e.clientX - r.left) / r.width) * n)));
    const m = months[i];
    show(e, (
      <>
        <div className="tt-head">{m.t}{m.rec ? " · NBER RECESSION" : ""}</div>
        <div className="tt-row"><span>cycle heat</span><b>{m.hc ?? "—"}</b></div>
        <div className="tt-row"><span>sovereign heat</span><b>{m.hs ?? "—"}</b></div>
        <div className="tt-row"><span>composite</span><b>{m.h ?? "—"}</b></div>
        <div className="tt-row"><span>fwd-12m max DD</span><b>{m.f != null ? `${m.f}%` : "open"}</b></div>
        <div className="tt-row"><span>small cycle</span><b>{m.s != null ? SC_STATUS_NAME[m.s] : "n/a"}</b></div>
        {m.trig.length > 0 && <div className="tt-trigs">{m.trig.join(" · ")}</div>}
      </>
    ));
  };

  return (
    <div className="chart-block">
      <div className="chart-controls">
        <div className="chart-window-btns">
          {WINDOWS.map(x => (
            <button key={x.key} className={`chart-btn${win === x.key ? " active" : ""}`} onClick={() => setWin(x.key)}>{x.key}</button>
          ))}
        </div>
        <div className="chart-episode-chips">
          <span className="chart-chip-label">EPISODES</span>
          {EPISODES.filter(ep => PANEL.some(m => m.t >= ep.from && m.t <= ep.to)).map(ep => (
            <button key={ep.key} className={`chart-chip${episode === ep.key ? " active" : ""}`}
              onClick={() => setEpisode(episode === ep.key ? null : ep.key)}>{ep.title}</button>
          ))}
        </div>
      </div>

      <div className="chart-scroller-wrap">
        <div className="chart-scroller" ref={ref} style={fit ? { overflowX: "hidden" } : undefined}>
          <div style={{ width: fit ? "100%" : width }}>
            <div className="chart-panel-title">CYCLE HEAT vs SOVEREIGN HEAT · 0–100 · POINT-IN-TIME REPLAY {PANEL[0].t} → {PANEL[n - 1].t}</div>
            <svg viewBox={`0 0 ${width} ${H1}`} width="100%" height={H1} preserveAspectRatio="none"
              onMouseMove={hover} onMouseLeave={hide} role="img" aria-label="Composite heat timeline">
              {recessionBands(months, xAt, PT, H1 - PT - PB)}
              {[0, 50, 100].map(g => (
                <line key={g} x1={0} x2={width} y1={yHeat(g)} y2={yHeat(g)} stroke="var(--grid-line)" strokeWidth={1} />
              ))}
              <path d={heatArea} fill="var(--red)" opacity={0.08} />
              <polyline points={sovPts} fill="none" stroke="var(--amber)" strokeWidth={1.4} strokeLinejoin="round" vectorEffect="non-scaling-stroke" opacity={0.8} />
              <polyline points={cyclePts} fill="none" stroke="var(--red)" strokeWidth={1.6} strokeLinejoin="round" vectorEffect="non-scaling-stroke" />
              {yearLabels.map(l => (
                <text key={l.i} x={xAt(l.i)} y={H1 - 4} fontSize={9} fill="var(--text-faint)" textAnchor="middle" fontFamily="var(--mono)">{l.yy}</text>
              ))}
            </svg>
            <div className="chart-panel-title" style={{ marginTop: 8 }}>FORWARD 12M MAX DRAWDOWN · % (WHAT THE MARKET DID NEXT)</div>
            <svg viewBox={`0 0 ${width} ${H2}`} width="100%" height={H2} preserveAspectRatio="none"
              onMouseMove={hover} onMouseLeave={hide} role="img" aria-label="Forward 12 month max drawdown">
              {recessionBands(months, xAt, PT, H2 - PT - PB)}
              {[0, -25, -50].map(g => (
                <line key={g} x1={0} x2={width} y1={yDD(g)} y2={yDD(g)} stroke="var(--grid-line)" strokeWidth={1} />
              ))}
              <polyline points={ddPts} fill="none" stroke="var(--blue)" strokeWidth={1.6} strokeLinejoin="round" vectorEffect="non-scaling-stroke" />
              {yearLabels.map(l => (
                <text key={l.i} x={xAt(l.i)} y={H2 - 4} fontSize={9} fill="var(--text-faint)" textAnchor="middle" fontFamily="var(--mono)">{l.yy}</text>
              ))}
            </svg>
          </div>
        </div>
        <div className="chart-yaxis">
          <div className="chart-yaxis-col" style={{ height: H1 }}>
            {[100, 50, 0].map(g => <span key={g} style={{ top: yHeat(g) - 6 }}>{g}</span>)}
          </div>
          <div className="chart-yaxis-col" style={{ height: H2, marginTop: 26 }}>
            {[0, -25, -50].map(g => <span key={g} style={{ top: yDD(g) - 6 }}>{g}</span>)}
          </div>
        </div>
      </div>
      <div className="chart-legend">
        <span><span className="chart-swatch" style={{ background: "var(--red)" }} /> CYCLE HEAT (SC·S6·PC·SoV·S5)</span>
        <span><span className="chart-swatch" style={{ background: "var(--amber)" }} /> SOVEREIGN HEAT (S8·S7·S3·TAX·JP)</span>
        <span><span className="chart-swatch" style={{ background: "var(--blue)" }} /> FWD-12M MAX DD</span>
        <span><span className="chart-swatch chart-swatch-band" /> NBER RECESSION</span>
        <span className="chart-legend-note">scroll to pan · hover to read · click an episode to replay it month-by-month</span>
      </div>

      {episode && <EpisodeReplay ep={EPISODES.find(e => e.key === episode)!} />}
      {node}
    </div>
  );
}

/** Month-by-month replay drawer — the backtest case study for any episode. */
function EpisodeReplay({ ep }: { ep: { title: string; from: string; to: string } }) {
  const { show, hide, node } = useTooltip();
  const months = PANEL.filter(m => m.t >= ep.from && m.t <= ep.to);
  const n = months.length;
  const W = 940, H = 200, PT = 26, PB = 22;
  const bw = W / n;
  const yAt = (v: number) => PT + (1 - v / 100) * (H - PT - PB);

  return (
    <div className="episode-drawer">
      <div className="chart-panel-title">EPISODE REPLAY · {ep.title.toUpperCase()} · {ep.from} → {ep.to} · BARS = HEAT, COLORED BY SMALL-CYCLE STATUS · ▲ T1 ■ T2 ● T3</div>
      <svg viewBox={`0 0 ${W} ${H}`} width="100%" role="img" aria-label={`Month by month replay of ${ep.title}`} onMouseLeave={hide}>
        {[0, 50, 100].map(g => (
          <line key={g} x1={0} x2={W} y1={yAt(g)} y2={yAt(g)} stroke="var(--grid-line)" strokeWidth={1} />
        ))}
        {months.map((m, i) => {
          const x = i * bw;
          const h = Math.max(1.5, yAt(0) - yAt(m.h ?? 0));
          const tiers = [...new Set(m.trig.map(s => Number(s[1])))].sort();
          return (
            <g key={m.t}
              onMouseMove={e => show(e, (
                <>
                  <div className="tt-head">{m.t}{m.rec ? " · NBER RECESSION" : ""}</div>
                  <div className="tt-row"><span>SC phase</span><b>{m.ph ?? "—"}</b></div>
                  <div className="tt-row"><span>NFP 3mma</span><b>{m.nfp != null ? `${m.nfp}k` : "—"}</b></div>
                  <div className="tt-row"><span>Sahm gap</span><b>{m.sahm}</b></div>
                  <div className="tt-row"><span>claims y/y</span><b>{m.claims != null ? `${m.claims}%` : "—"}</b></div>
                  <div className="tt-row"><span>heat</span><b>{m.h ?? "—"}</b></div>
                  <div className="tt-row"><span>fwd-12m DD</span><b>{m.f != null ? `${m.f}%` : "—"}</b></div>
                  {m.trig.length > 0 && <div className="tt-trigs">{m.trig.join(" · ")}</div>}
                </>
              ))}>
              {m.rec === 1 && <rect x={x} y={PT} width={bw} height={H - PT - PB} fill="var(--rec-band)" />}
              <rect x={x + 1.5} y={yAt(m.h ?? 0)} width={Math.max(1, bw - 3)} height={h} rx={1.5}
                fill={m.s != null ? SC_STATUS_COLOR[m.s] : "var(--text-ghost)"} opacity={0.9} />
              {tiers.map((tier, k) => {
                const mx = x + bw / 2, my = yAt(m.h ?? 0) - 7 - k * 10;
                if (tier === 1) return <path key={tier} d={`M${mx - 3.5},${my + 3} L${mx + 3.5},${my + 3} L${mx},${my - 3.5} Z`} fill="var(--red)" />;
                if (tier === 2) return <rect key={tier} x={mx - 2.8} y={my - 2.8} width={5.6} height={5.6} fill="var(--amber)" />;
                return <circle key={tier} cx={mx} cy={my} r={2.6} fill="var(--blue)" />;
              })}
              {(m.t.endsWith("-01") || m.t.endsWith("-07")) && (
                <text x={x + bw / 2} y={H - 6} fontSize={8.5} fill="var(--text-faint)" textAnchor="middle" fontFamily="var(--mono)">{m.t}</text>
              )}
            </g>
          );
        })}
      </svg>
      {node}
    </div>
  );
}
